version: '3'
services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  server:
      build: ./server
      tty: true
      working_dir: /home/node/server
      container_name: 'server'
      environment:
        - NODE_ENV=development
      ports:
        - "${PORT}:${PORT}"
      volumes:
          - "./server:/home/node/server"
      depends_on:
        - mongodb


